package com.techdevweb.techdevbackend.Notification.Enum;

public enum NotificationType {
    EVENT_REGISTRATION_CONFIRMED,
    EVENT_REGISTRATION_PENDING,
    EVENT_REGISTRATION_APPROVED,
    EVENT_REGISTRATION_REJECTED,
    EVENT_CANCELLED,
    EVENT_REMINDER,
    EVENT_UPDATED,

    APPLICATION_RECEIVED,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED,

    PROJECT_APPROVED,
    PROJECT_REJECTED,

    USER_WELCOME
}
